package com.altalha.hangman

object GameConstants {
    val words = listOf(
        "Barguna",
        "Bagerhat",
        "Bandarban",
        "Barisal",
        "Bhola",
        "Bogra",
        "Brahmanbaria",
        "Chandpur",
        "Chapai Nawabganj",
        "Chittagong",
        "Chuadanga",
        "Comilla",
        "Cox's Bazar",
        "Dhaka",
        "Dinajpur",
        "Faridpur",
        "Feni",
        "Gaibandha",
        "Gazipur",
        "Gopalganj",
        "Habiganj",
        "Jamalpur",
        "Jessore",
        "Jhalokati",
        "Jhenaidah",
        "Joypurhat",
        "Khagrachhari",
        "Khulna",
        "Kishoreganj",
        "Kurigram",
        "Kushtia",
        "Lakshmipur",
        "Lalmonirhat",
        "Madaripur",
        "Magura",
        "Manikganj",
        "Meherpur",
        "Moulvibazar",
        "Munshiganj",
        "Mymensingh",
        "Naogaon",
        "Narail",
        "Narayanganj",
        "Narsingdi",
        "Natore",
        "Netrokona",
        "Nilphamari",
        "Noakhali",
        "Pabna",
        "Panchagarh",
        "Patuakhali",
        "Pirojpur",
        "Rajbari",
        "Rajshahi",
        "Rangamati",
        "Rangpur",
        "Satkhira",
        "Shariatpur",
        "Sherpur",
        "Sirajganj",
        "Sunamganj",
        "Sylhet",
        "Tangail",
        "Thakurgaon"
        )

    val hints = listOf(
        "Start with B and famous for fresh foods",
        "A place of Heritage site with Mosque",
        "A Natural Lake 3000 feet above the sea level",
        "Has a lake with artificial island",
        "Largest island of Bangladesh",
        "Has a well known urban archaeological site",
        "Has a mosque founded by Shah Arif in 1662",
        "Capital town for Hilsa",
        "City of Mango",
        "Second largest city of Bangladesh",
        "First Capital of Bangladesh",
        "Known for Ras Malai",
        "Biggest tourism spot in Bangladesh",
        "City of Mosque",
        )
}